server:
  port: 8080
  servlet:
    context-path: /laklu

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/laklu"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-Auto: update
    show-sql: true